#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#
# Modified by Kevin Song specifically for TACC systems

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#Load bart theme
autoload -Uz promptinit
promptinit
prompt sorin

######################
# User configuration #
######################

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

unsetopt correct_all
unsetopt correct

#History limits
HISTSIZE=1000
SAVEHIST=4000

### Set up auto Dirstack ####
#Use dirs -v to list and cd -<#> to revisit
setopt autopushd pushdsilent pushdtohome
setopt pushdignoredups # Ignore duplicate entries
setopt pushdminus # This reverts the +/- operators.
#### End autodirstack ####

setopt extended_glob

TERM='xterm-256color'
alias dirs="dirs -v"

##Hash R so that autocd doesn't bite us in the arse
hash R &> /dev/null

##Disable GREP_OPTIONS (annoying warnings)
unset GREP_OPTIONS

#Change output of time to be bash-like
TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

# Enable usage of autojump
export FPATH="$FPATH:/opt/local/share/zsh/site-functions/"
if [ -f /opt/local/etc/profile.d/autojump.zsh ]; then
    . /opt/local/etc/profile.d/autojump.zsh
fi

# Hash SSH config and known_hosts to get SSH completion lists
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/known_hosts ]]; then
  h=($h ${${${(f)"$(cat ~/.ssh/known_hosts{,2} || true)"}%%\ *}%%,*}) 2>/dev/null
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
fi

unsetopt CDABLE_VARS

## TACC CONFIGS

alias tma="tmux attach"
export EMAIL="ksong+taccnotify@ices.utexas.edu"
function submit_tacc_job_with_notification(){
	sbatch --mail-user="$EMAIL" --mail-type=BEGIN,END "$1"
}
alias sbatch-mail=submit_tacc_job_with_notification
