#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#Load bart theme
autoload -Uz promptinit
promptinit
prompt paradox

######################
# User configuration #
######################


# You may need to manually set your language environment
export LANG=en_US.UTF-8

unsetopt correct_all  
unsetopt correct

#History limits
HISTSIZE=1000
SAVEHIST=4000

### Set up auto Dirstack ####
#Use dirs -v to list and cd -<#> to revisit
setopt autopushd pushdsilent pushdtohome
setopt pushdignoredups # Ignore duplicate entries
setopt pushdminus # This reverts the +/- operators.
#### End autodirstack ####

setopt extended_glob

TERM='xterm-256color'
alias dirs="dirs -v"

##Hash R so that autocd doesn't bite us in the arse
hash R &> /dev/null

##Disable GREP_OPTIONS (annoying warnings)
unset GREP_OPTIONS

#Change output of time to be bash-like
TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

unsetopt IGNORE_EOF
setopt clobber
unsetopt CDABLE_VARS

# Hash SSH config and known_hosts to get SSH completion lists
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/known_hosts ]]; then
  h=($h ${${${(f)"$(cat ~/.ssh/known_hosts{,2} || true)"}%%\ *}%%,*}) 2>/dev/null
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
fi

# Rawrrrr >:3
alias kk="bg && disown"

# Utilities for ccache
CCACHE_PATH=/usr/lib/ccache/bin
ccache_on(){
  PATH=$CCACHE_PATH:$PATH
  export PATH
}
ccache_off(){
  PATH=$(echo $PATH | sed -e 's_'$CCACHE_PATH':__')
  export PATH
}

# Make make (hah!) use all our processors by default
export MAKEFLAGS="-j$(nproc --all)"

# Stuff for z yo
[[ -r "/usr/share/z/z.sh" ]] && source /usr/share/z/z.sh

# Keychain for easy SSH
eval $(keychain --eval --quiet --noask --nogui)

# Command not found
source /usr/share/doc/pkgfile/command-not-found.zsh

# Change default editors
export EDITOR=vim
export VISUAL=vim

# Check that path is valid
PROBLEMS="false"
SPLITPATH=("${(@s/:/)PATH}")
for DIR in ${SPLITPATH[@]}; do
    if [ ! -d "$DIR" ]; then
        echo "WARN: Directory $DIR in PATH does not seem to exist!"
        PROBLEMS="true"
    fi
done
if [ "$PROBLEMS" = "true" ]; then
    echo "Problems detected in PATH. Fix them in ~/.zprofile"
fi

